### ISSUE TITLE
ChatSpace挙動確認

### ISSUE THREAD

**Issue by david-masa** [david-masa/chat-space#19]
#IIPアドレス
13.112.125.113

**Comment by mo1015** [comment]
高岡さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**○contents上部に線が入っていない**
<img width="421" alt="修正" src="https://user-images.githubusercontent.com/62644781/79959551-391c5700-84bf-11ea-90f1-4790b48ea0f6.png">
<img width="421" alt="線見本" src="https://user-images.githubusercontent.com/62644781/79959563-3e79a180-84bf-11ea-9845-9c307a16dbd5.png">
**○リロードすると、投稿メッセージが下に偏ってしまう**
<img width="415" alt="スクリーンショット 2020-04-22 17 30 44" src="https://user-images.githubusercontent.com/62644781/79959586-433e5580-84bf-11ea-8804-c404f30958be.png">


修正でき次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by david-masa** [comment]
修正いたしました。
ご確認、よろしくお願いいたします。

**Comment by mo1015** [comment]
再提出ありがとうございます！
前回指摘箇所　**○contents上部に線が入っていない**
のみ修正確認ができませんでした。
本番環境で実装できているかもう一度確認をお願いします！

↓参考仕様書
<img width="735" alt="cs仕様書" src="https://user-images.githubusercontent.com/62644781/79962721-60752300-84c3-11ea-8d30-18ef43500e30.png">


修正でき次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by david-masa** [comment]
contents上部ということでしたが、main-headerの下部に実装しています。
またサンプルのページでは、色が#eeeで白でしたので、同じような色の#ffffffを$color1のような形で追記しています。

gyazoは本番環境での検証ページです。
https://gyazo.com/4d63183dee5fc549696772a7f4ed6569

御確認、よろしくお願いします！

**Comment by mo1015** [comment]
画像提出と実装説明ありがとうございます！
問題ございませんのでLGTMとさせて頂きます🎉
おめでとうございます！

**Comment by david-masa** [comment]
ありがとうございます！
